# Generated by Django 4.2.7 on 2023-12-16 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecolink_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=200)),
                ('attendees', models.ManyToManyField(related_name='joined_events', to='ecolink_app.user')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='ecolink_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
