# Generated by Django 4.2.7 on 2023-12-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecolink_app', '0003_remove_campaign_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='location',
            new_name='area',
        ),
        migrations.AddField(
            model_name='campaign',
            name='state',
            field=models.CharField(default='Texas', max_length=20),
        ),
    ]
