# Generated by Django 4.2.7 on 2023-12-17 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecolink_app', '0004_rename_location_campaign_area_campaign_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='state',
        ),
        migrations.AddField(
            model_name='campaign',
            name='chat_room_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='contact_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='ecolink_app.user'),
        ),
    ]
