# Generated by Django 4.2.7 on 2023-12-17 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecolink_app', '0009_city_campaign_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_campaigns', to='ecolink_app.city'),
        ),
    ]
