# Generated by Django 4.2.7 on 2023-12-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecolink_app', '0010_alter_campaign_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='chat_room_link',
        ),
    ]
